param(
  [string]$BaseUrl = "http://localhost:5680",
  [string]$Role = "L3_engineer",
  [string]$TaskType = "doc",
  [string]$Complexity = "normal",
  [string]$ModelOverride = "auto",
  [string]$TaskPackPath = ""
)

$ErrorActionPreference = "Stop"

function Post-Json {
  param(
    [string]$Url,
    [hashtable]$Body
  )
  $json = $Body | ConvertTo-Json -Depth 20
  Invoke-RestMethod -Method Post -Uri $Url -Body $json -ContentType "application/json" -Proxy $null
}

Write-Host "[smoke-secondary] base=$BaseUrl" -ForegroundColor Cyan

if (-not $TaskPackPath) {
  $now = Get-Date -Format "yyyyMMdd-HHmmss"
  $taskId = "T-SMOKE-$now"
  $logOut = "docs/05_logs/smoke-secondary-$now.md"

  $composeBody = @{
    task_id = $taskId
    title = "Smoke: secondary compose-taskpack -> execute-task"
    level = "L3"
    owner = "L0_producer"
    executor = $Role
    reviewer = "L2_tools_lead"
    task_type = $TaskType
    complexity = $Complexity
    model_override = $ModelOverride
    execution_runtime = "wsl"
    requires_mcp = "false"
    outcome = "Create a smoke log file: $logOut"
    # Use raw repo-relative paths here (no [`file`] tags) to match current guardrail parsing.
    allowed_inputs = @(
      "docs/02_specs/pipelines/n8n_cursor_cli_pipeline_spec.md"
      "docs/02_specs/pipelines/factory_pipeline_spec.md"
    )
    deliverables = @(
      "$logOut"
    )
    constraints = @(
      "Do not modify any file outside Deliverables"
      "Do not modify docs/00_charter/** or docs/01_bibles/**"
      "Output must be valid UTF-8 markdown"
    )
    acceptance = @(
      "[ ] File $logOut created"
      "[ ] File contains timestamp and states entry mode is 5680-single-entry"
    )
    notes = "This taskpack is generated by tools/n8n/smoke-secondary.ps1"
  }

  $composeUrl = "$BaseUrl/webhook/compose-taskpack"
  Write-Host "[smoke-secondary] POST $composeUrl" -ForegroundColor Cyan
  $composeRes = Post-Json -Url $composeUrl -Body $composeBody
  $TaskPackPath = $composeRes.task_pack_path
  if (-not $TaskPackPath) {
    throw "compose-taskpack did not return task_pack_path"
  }
  Write-Host "[smoke-secondary] task_pack_path=$TaskPackPath" -ForegroundColor Green
}

$execBody = @{
  task_pack_path = $TaskPackPath
  role = $Role
  task_type = $TaskType
  complexity = $Complexity
  model_override = $ModelOverride
}

$execUrl = "$BaseUrl/webhook/execute-task"
Write-Host "[smoke-secondary] POST $execUrl" -ForegroundColor Cyan
Write-Host "[smoke-secondary] payload task_pack_path=$TaskPackPath role=$Role task_type=$TaskType complexity=$Complexity model_override=$ModelOverride" -ForegroundColor DarkGray
$execRes = Post-Json -Url $execUrl -Body $execBody

Write-Host "[smoke-secondary] response:" -ForegroundColor Green
$execRes | ConvertTo-Json -Depth 30


